apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: frontend
    image: react-image
    resources:
      limits:
        memory: 200Mi
        cpu: "1"
      requests:
        memory: 200Mi
        cpu: "1"
  - name: db
    image: db-image
    resources:
      limits:
        memory: 200Mi
        cpu: "1"
      requests:
        memory: 200Mi
        cpu: "1"
