apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: my-app
    image: my-image:latest
    volumeMounts:
    - name: my-volume
      mountPath: /data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
