apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-container
            image: my-image
            command:
            - /bin/sh
            - -c
            - echo "Hello, world!"
          restartPolicy: OnFailure
