apiVersion: batch/v1
kind: Job
metadata:
  name: db-setup
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: db-setup
        image: db-image
      restartPolicy: Never
      activeDeadlineSeconds: 300
