apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox-container
      image: registry.k8s.io/busybox
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      livenessProbe:
        exec:
          command: ['echo', 'hello']
        initialDelaySeconds: 5
        periodSeconds: 10
