apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: db
    image: db-image:latest
    env:
    - name: DB_USERNAME
      value: username
    - name: DB_PASSWORD
      value: password
